---
  - name: "install dependencies."
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: Install Node
    shell: |
      sudo apt update
      sudo apt install nodejs npm
      node --version
      npm --version      


  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: Copy backend dist files web server
    copy:
      src: files/backend
      dest: /home/ubuntu/
      remote_src: yes
      directory_mode: yes

  - name: Install Node
    shell: |
      cd /home/ubuntu/backend
      npm install
  - name: Build Node
    shell: |
      cd /home/ubuntu/backend
      npm run build
  
  - name: Start PM2
    shell: |
      cd /home/ubuntu/backend 
      pm2 start npm --name backend -- start